export declare const colors: {
    buttonGradient: string;
    tooltipGradient: string;
    disabledGradient: string;
    tooltipBorder: string;
    disabledText: string;
    darkBlue: string;
    lightBlue: string;
    green: string;
    white: string;
    modal: string;
    checkboxChecked: string;
    checkboxUnchecked: string;
    selectedButton: string;
    scrollBarTrack: string;
    scrollBarThumb: string;
    scrollBarThumbHover: string;
    scrollBarBorder: string;
    alertSuccess: string;
    alertWarning: string;
    alertInfo: string;
    alertError: string;
    dark: string;
    medium: string;
    light: string;
    blueMenu: string;
    greenIcon: string;
    buttonMenu: string;
    lightNenu: string;
    middleMenu: string;
    darkMenu: string;
    textMenu: string;
    turquois: string;
    greenBase: string;
    blueSurface: string;
    lightSurface: string;
    alertBrown: string;
    disabledTextOld: string;
};
export declare const shadows: {
    modalShadow: string;
    buttonShadow: string;
    checkbosShadow: string;
};
export type Color = typeof colors;
export type Shadow = typeof shadows;
